#!/bin/sh -e

./configure \
	--prefix=/usr \
	--without-perl5 \
	--without-octave \
	--without-scilab \
	--without-java \
	--without-javascript \
	--without-android \
	--without-guile \
	--without-mzscheme \
	--without-ruby \
	--without-php \
	--without-ocaml \
	--without-csharp \
	--without-lua \
	--without-r \
	--without-go \
	--without-go \

make
make DESTDIR="$1" install
