#!/bin/sh -e

for p in *.patch
do
    patch -p1 < "$p"
done

rm -f common/source_files/mozconfig
cp -r common/source_files/* ./

# Remove libc header which conflicts with 7 or so Linux
# kernel headers. See: https://github.com/kisslinux/repo/issues/207
sed -i '/net\/if/d' \
    dom/media/webrtc/transport/third_party/nICEr/src/stun/addrs-netlink.c

# Disabling Pocket
sed -i "s/'pocket'/#'pocket'/g" browser/components/moz.build
sed -i 's#SaveToPocket.init();#// SaveToPocket.init();#g' browser/components/BrowserGlue.jsm

# Remove Internal Plugin Certificates
sed "/if (aCert.organizationalUnit/,+3d" -i toolkit/mozapps/extensions/internal/XPIInstall.jsm

# allow SearchEngines option in non-ESR builds
sed -i 's#"enterprise_only": true,#"enterprise_only": false,#g' browser/components/enterprisepolicies/schemas/policies-schema.json

_settings_services_sed='s#firefox.settings.services.mozilla.com#f.s.s.m.c.qjz9zk#g'

# stop some undesired requests (https://gitlab.com/librewolf-community/browser/common/-/issues/10)
sed "$_settings_services_sed" -i browser/components/newtab/data/content/activity-stream.bundle.js
sed "$_settings_services_sed" -i modules/libpref/init/all.js
sed "$_settings_services_sed" -i services/settings/Utils.jsm
sed "$_settings_services_sed" -i toolkit/components/search/SearchUtils.jsm

# Build autoconf 2.13 for Firefox's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

# Build yasm for Firefox's sole use.
# Firefox is the only package which needs it
# and upstream is kinda dead.
(
    cd yasm

    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)
export PATH="$PWD/junk/bin:$PATH"

# Bypass 'ccache' as it's totally useless when building
# Firefox and only slows things down.
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/librewolf"
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"

export MACH_USE_SYSTEM_PYTHON=1
export MOZ_DEBUG_FLAGS=-g0
export MOZ_NOSPAM=1

./mach configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-optimize="$CFLAGS -w" \
    --enable-install-strip \
    --enable-strip \
    --enable-rust-simd \
    --enable-application=browser \
    --enable-release \
    --enable-alsa \
    --enable-default-toolkit=cairo-gtk3-wayland \
    --with-app-name=librewolf \
    --with-app-basename=Librewolf \
    --with-branding=browser/branding/librewolf \
    --without-system-nspr \
    --without-system-nss \
    --with-system-jpeg \
    --with-system-zlib \
    --with-system-png \
    --without-system-libvpx \
    --with-system-pixman \
    --with-system-ffi \
    --disable-profiling \
    --disable-accessibility \
    --disable-tests \
    --disable-system-extension-dirs \
    --disable-parental-controls \
    --disable-debug-symbols \
    --disable-callgrind \
    --disable-vtune \
    --disable-elf-hack \
    --disable-gold \
    --disable-jemalloc \
    --disable-pulseaudio \
    --disable-crashreporter \
    --disable-updater \
    --disable-dbus \
    --disable-eme \
    --disable-necko-wifi

./mach build
DESTDIR="$1" ./mach install

cp -r settings/* "$1/usr/lib/librewolf/"

# Remove a lot of uneeded "stuff".
rm -rf "$1/usr/include"
rm -rf "$1/usr/lib/librewolf-devel"
rm -rf "$1/usr/share/idl"
rm -rf "$1/usr/lib/librewolf/gtk2" # Drop GTK+2 runtime dependency.
rm -f  "$1/usr/lib/librewolf/browser/features/fxmonitor@mozilla.org.xpi"
rm -f  "$1/usr/lib/librewolf/browser/features/screenshots@mozilla.org.xpi"
rm -f  "$1/usr/lib/librewolf/browser/features/webcompat-reporter@mozilla.org.xpi"
rm -f  "$1/usr/lib/librewolf/browser/features/webcompat@mozilla.org.xpi"
rm -f  "$1/usr/lib/librewolf/browser/features/doh-rollout@mozilla.org.xpi"
