#!/bin/sh -e

export DESTDIR="$1"

meson \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	-Dvalgrind=disabled \
	-Dpython=enabled \
	. output

ninja -C output
ninja -C output install
