#!/bin/sh

for patch in patches/*
do
    echo "Applying $patch"
    patch -p1 < $patch
done

mkdir -p third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/node

use_system="
    ffmpeg
    flac
    fontconfig
    freetype
    harfbuzz-ng
    libdrm
    libevent
    libjpeg
    libpng
    libwebp
    libxml
    libxslt
    opus
    "
for _lib in $use_system libjpeg_turbo; do
    find . -type f -path "*third_party/$_lib/*" \
        \! -path "*third_party/$_lib/chromium/*" \
        \! -path "*third_party/$_lib/google/*" \
        \! -path './base/third_party/icu/*' \
        \! -path './third_party/libxml/*' \
        \! -path './third_party/pdfium/third_party/freetype/include/pstables.h' \
        \! -path './third_party/harfbuzz-ng/utils/hb_scoped.h' \
        \! -regex '.*\.\(gn\|gni\|isolate\|py\)' \
        -delete
done

python2 build/linux/unbundle/replace_gn_files.py --system-libraries \
    $use_system
third_party/libaddressinput/chromium/tools/update-strings.py

_c="is_clang=true
    use_sysroot=false
    treat_warnings_as_errors=false
    fatal_linker_warnings=false
    use_custom_libcxx=false
    use_gold=false
    use_allocator=\"none\"
    use_allocator_shim=false
    use_vaapi=true
    use_cups=false
    use_gnome_keyring=false
    is_debug=false"

CC="${CC:-clang}" CXX="${CXX:-clang++}" LD="${CXX:-clang++}" \
    python2 tools/gn/bootstrap/bootstrap.py -s -v --gn-gen-args "$_c"

AR="ar" CC="clang" CXX="clang++" LD="clang++" NM=/usr/bin/nm \
    out/Release/gn gen out/Release --args="blink_symbol_level=0 clang_use_chrome_plugins=false custom_toolchain=\"//build/toolchain/linux/unbundle:default\" enable_hangout_services_extension=true enable_nacl_nonsfi=false enable_nacl=false enable_precompiled_headers=false fatal_linker_warnings=false ffmpeg_branding=\"Chrome\" fieldtrial_testing_like_official_build=true gold_path=\"/usr/bin/ld.gold\" host_toolchain=\"//build/toolchain/linux/unbundle:default\" icu_use_data_file=true is_clang=true is_component_build=false is_debug=false is_desktop_linux=true proprietary_codecs=false symbol_level=0 treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_cups=false use_custom_libcxx=false use_gnome_keyring=false use_gold=false use_lld=false use_pulseaudio=false use_sysroot=false use_system_harfbuzz=true enable_js_type_check=false" --script-executable=python2

ninja -C out/Release chrome chrome_sandbox chromedriver
ninja -C out/Release install
